# JSON examples and exercise
****
+ get familiar with packages for dealing with JSON
+ study examples with JSON strings and files 
+ work on exercise to be completed and submitted 
****
+ reference: http://pandas.pydata.org/pandas-docs/stable/io.html#io-json-reader
+ data source: http://jsonstudio.com/resources/
****

In [ ]:
import pandas as pd

## imports for Python, Pandas

In [ ]:
import json
from pandas.io.json import json_normalize

## JSON example, with string

+ demonstrates creation of normalized dataframes (tables) from nested json string
+ source: http://pandas.pydata.org/pandas-docs/stable/io.html#normalization

In [ ]:
# define json string
data = [{'state': 'Florida', 
         'shortname': 'FL',
         'info': {'governor': 'Rick Scott'},
         'counties': [{'name': 'Dade', 'population': 12345},
                      {'name': 'Broward', 'population': 40000},
                      {'name': 'Palm Beach', 'population': 60000}]},
        {'state': 'Ohio',
         'shortname': 'OH',
         'info': {'governor': 'John Kasich'},
         'counties': [{'name': 'Summit', 'population': 1234},
                      {'name': 'Cuyahoga', 'population': 1337}]}]

In [ ]:
# use normalization to create tables from nested element
json_normalize(data, 'counties')

In [ ]:
# further populate tables created from nested element
json_normalize(data, 'counties', ['state', 'shortname', ['info', 'governor']])

****
## JSON example, with file

+ demonstrates reading in a json file as a string and as a table
+ uses small sample file containing data about projects funded by the World Bank 
+ data source: http://jsonstudio.com/resources/

In [ ]:
# load json as string
json.load((open('data/world_bank_projects_less.json')))

In [ ]:
# load as Pandas dataframe
sample_json_df = pd.read_json('data/world_bank_projects_less.json')
sample_json_df

****
## JSON exercise

Using data in file 'data/world_bank_projects.json' and the techniques demonstrated above,
1. Find the 10 countries with most projects
2. Find the top 10 major project themes (using column 'mjtheme_namecode')
3. In 2. above you will notice that some entries have only the code and the name is missing. Create a dataframe with the missing names filled in.

In [2]:
import pandas as pd
import json
from pandas.io.json import json_normalize
import numpy as np
## Finding the top 10 countries with the most projects
sample_json_df = pd.read_json('data/world_bank_projects.json')
s = sample_json_df.groupby('countryname').size().sort_values(ascending = False)
s = s.head(10)
print 'Top 10 countries with the most project'
s

Top 10 countries with the most project

countryname
People's Republic of China         19
Republic of Indonesia              19
Socialist Republic of Vietnam      17
Republic of India                  16
Republic of Yemen                  13
Nepal                              12
People's Republic of Bangladesh    12
Kingdom of Morocco                 12
Africa                             11
Republic of Mozambique             11
dtype: int64

In [15]:
## Loading and Normalizing the JSON files
temp = json.load((open('data/world_bank_projects.json')))
table = json_normalize(temp,'mjtheme_namecode')

# creating a copy of table
table_copy = table
table_copy2 = json_normalize(temp,'mjtheme_namecode')

In [16]:
# this is the table which contains the code and name  of the project
table['name'].replace('', np.nan, inplace=True)
table.dropna(subset=['name'], inplace=True)
table.drop_duplicates()
print 'Table having unique code and name of the project'
ValueTable = table.drop_duplicates()
ValueTable

Table having unique code and name of the project

    code                                          name
0      8                             Human development
2      1                           Economic management
3      6         Social protection and risk management
4      5                         Trade and integration
5      2                      Public sector governance
6     11  Environment and natural resources management
8      7                   Social dev/gender/inclusion
11     4      Financial and private sector development
18    10                             Rural development
53     9                             Urban development
252    3                                   Rule of law

In [17]:
## Finding the top 10 projects

codes = table_copy['code'].value_counts().sort_values(ascending = False).index.tolist()
print 'The top projects are :-'
for i in codes:
    name = table.loc[table['code'] == i, 'name'].iloc[0]
    print name

The top projects are :-
Environment and natural resources management
Rural development
Human development
Public sector governance
Social protection and risk management
Financial and private sector development
Social dev/gender/inclusion
Trade and integration
Urban development
Economic management
Rule of law

In [21]:
## Filling the data frame with the missing names of the project
for i in range(0,len(table_copy2)):
    if table_copy2.loc[i,'name'] == '':
        code = table_copy2.loc[i,'code']
        name = str(ValueTable.loc[ValueTable['code'] == code, 'name'].iloc[0])
        table_copy2.loc[i,'name'] = name
print 'The filled Data frame'
table_copy2

The filled Data frame

     code                                          name
0       8                             Human development
1      11  Environment and natural resources management
2       1                           Economic management
3       6         Social protection and risk management
4       5                         Trade and integration
5       2                      Public sector governance
6      11  Environment and natural resources management
7       6         Social protection and risk management
8       7                   Social dev/gender/inclusion
9       7                   Social dev/gender/inclusion
10      5                         Trade and integration
11      4      Financial and private sector development
12      6         Social protection and risk management
13      6         Social protection and risk management
14      2                      Public sector governance
15      4      Financial and private sector development
16     11  Environment and natural resources management
17      8                             Human development
18     10                             Rural development
19      7                   Social dev/gender/inclusion
20      2                      Public sector governance
21      2                      Public sector governance
22      2                      Public sector governance
23     10                             Rural development
24      2                      Public sector governance
25     10                             Rural development
26      6         Social protection and risk management
27      6         Social protection and risk management
28     11  Environment and natural resources management
29      4      Financial and private sector development
...   ...                                           ...
1469    8                             Human development
1470    9                             Urban development
1471    6         Social protection and risk management
1472    6         Social protection and risk management
1473    9                             Urban development
1474    2                      Public sector governance
1475    2                      Public sector governance
1476   10                             Rural development
1477   11  Environment and natural resources management
1478    8                             Human development
1479    7                   Social dev/gender/inclusion
1480   11  Environment and natural resources management
1481    5                         Trade and integration
1482    6         Social protection and risk management
1483    8                             Human development
1484    4      Financial and private sector development
1485    7                   Social dev/gender/inclusion
1486    8                             Human development
1487    5                         Trade and integration
1488    2                      Public sector governance
1489    8                             Human development
1490   10                             Rural development
1491    6         Social protection and risk management
1492   10                             Rural development
1493   10                             Rural development
1494   10                             Rural development
1495    9                             Urban development
1496    8                             Human development
1497    5                         Trade and integration
1498    4      Financial and private sector development

[1499 rows x 2 columns]